module.exports = {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.webp",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 0,
    },
    {
      _id: "2",
      name: "Classic Shirt",
      category: "Pants",
      image: "/images/d1.webp",
      price: 50,
      brand: "Brooks Brothers",
      rating: 4.5,
      numReviews: 5,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d1.webp",
      price: 40,
      brand: "Nautica",
      rating: 3.5,
      numReviews: 15,
      countInStock: 10,
    },
    {
      _id: "4",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d1.webp",
      price: 40,
      brand: "Nautica",
      rating: 3.5,
      numReviews: 15,
      countInStock: 25,
    },
  ],
};
